### ISSUE TITLE
short list of future developments that I hope to be able to do

### ISSUE THREAD

**Issue by nickprock** [nickprock/pynuTS#10]
- Demos about missing values and anomaly detection
- hierarchical clustering
- simple time series generator
- windowing function

_**if you want to contribute to the development you are welcome**_

**Comment by nickprock** [comment]
First version of demos about missing values and anomaly detection **DONE**

***if you want to contribute to the development you are welcome***

**Comment by mallibus** [comment]
For the clustring demo I developed some primitives for ts generation. I was thinking of making a class of them. For now there are slopes and flat series with various types of noise, plus a serial binary symbols generator with noise.
I was thinking of adding combinations of periodic functions.
This can be my next contribution, if you agree. Suggestions on requirements and api are welcome!

**Comment by nickprock** [comment]
Ok @mallibus you could create a file generator.py and develop the module. Thanks 😉

**Comment by mallibus** [comment]
I am going to explore the sax encoding for a project, so I think I will start writing some unit tests for your module decomposition.py
and add the relevnt unit test file in the /test folder.
Then, If all goes well, I'd like to try clustering ts with sax encoding, as suggested in your [post](https://iaml.it/blog/serie-storiche-2-sax-encoding)
