### ISSUE TITLE
missing import from parent folder in SAX demo notebook

### ISSUE THREAD

**Issue by mallibus** [nickprock/pynuTS#13]
**Describe the bug**
SAX encoding demo notebook gives import error when running in the demo folder

**To Reproduce**
1. Install pynuTS
2. Run jupyter notebook, open SAXEncoding_Demo.ipynb
3. Execute the first two cells

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-079840d0f8a8> in <module>
      1 import pandas as pd
      2 import numpy as np
----> 3 from pynuTS.decomposition import NaiveSAX
```

ModuleNotFoundError: No module named 'pynuTS'

**Expected behavior**
Notebook should run with no errors

**Screenshots**
not needed I guess

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python Version  3.9 anaconda distribution

**Additional context**
not needed I guess

**Comment by nickprock** [comment]
Thanks @mallibus , usually I work on Ubuntu 18.04 and it's works fine. I check this on monday

**Comment by nickprock** [comment]
@mallibus I have reproduced your example of import on Windows 10 (python 3.9.6 anaconda distribution) and It works.

- download the repo
- open anaconda powershell
- pip install .\pynuTS-main.zip
- open python shell
- from pynuTS.decomposition import NaiveSAX
