### ISSUE TITLE
X DataFrame orientation is wrong

### ISSUE THREAD

**Issue by mallibus** [nickprock/pynuTS#15]
**Describe the bug**
The SAX encoding is performed along the wrong axis in the SAX demo

**To Reproduce**
1. Install pynuTS
2. Run jupyter notebook, open SAXEncoding_Demo.ipynb 
3. Execute until cell [25] 
4. Visualize the DataFrame X (see below)

![issue14](https://user-images.githubusercontent.com/45511108/125166749-49d8eb80-e19d-11eb-9407-5e3894964f26.PNG)

The anomaly labels are attached in the rows, but the time series are in the columns. 
Also the visualization in the last cell is wrong and confirms that the orientation of the dataframe is not correct

![issue14 1](https://user-images.githubusercontent.com/45511108/125166795-80af0180-e19d-11eb-896d-f9edb5887ad0.PNG)

**Expected behavior**
Either the labels are set on the columns, or the DataFrame is not transposed.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python Version 3.9 anaconda

**Additional context**
none to report

**Comment by nickprock** [comment]
I fixed this bug, work in the night isn't good for me
